manifest:
  remotes:
    - name: mouse
      url-base: https://github.com/paramSonawane
  projects:
    - name: zmk
      remote: mouse
      revision: upstream-mouse-support-linux
      import: app/west.yml
  self:
    path: config
